# Generated by Django 5.0.6 on 2024-08-23 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiscales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_fical', models.CharField(max_length=100, verbose_name='Nombres y Apellidos')),
                ('cargo_fiscal', models.TextField(null=True)),
                ('profesion', models.CharField(max_length=300, verbose_name='Especialidad')),
                ('ubicacion', models.TextField(null=True)),
                ('telefono', models.CharField(max_length=300, verbose_name='Telefono')),
                ('email', models.CharField(max_length=300, verbose_name='Email')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.TextField(null=True)),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('dias', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('Proceso', 'Proceso'), ('Falta_un_dia', 'Falta un dia'), ('Completado', 'Completado')], default='Proceso', max_length=20)),
                ('fiscales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gca.fiscales')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Paim')),
                ('jefe', models.CharField(max_length=255, verbose_name='Nombre de Encargado')),
                ('ubicacion', models.TextField(null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('image', models.ImageField(blank=True, default='imagen.jpg', null=True, upload_to='imagenes/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiariosReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.CharField(max_length=255, verbose_name='Nombre y Apellido')),
                ('f', models.DateField(max_length=255, verbose_name='Fecha')),
                ('vt', models.IntegerField()),
                ('ob1', models.TextField(blank=True, null=True)),
                ('plc_ex', models.IntegerField()),
                ('ob2', models.TextField(blank=True, null=True)),
                ('vr', models.IntegerField()),
                ('ob3', models.TextField(blank=True, null=True)),
                ('mta', models.IntegerField()),
                ('ob4', models.TextField(blank=True, null=True)),
                ('mdua', models.IntegerField()),
                ('ob5', models.TextField(blank=True, null=True)),
                ('mn', models.IntegerField()),
                ('ob6', models.TextField(blank=True, null=True)),
                ('rp', models.IntegerField()),
                ('ob7', models.TextField(blank=True, null=True)),
                ('nd', models.IntegerField()),
                ('ob8', models.TextField(blank=True, null=True)),
                ('paim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gca.paim')),
            ],
        ),
        migrations.CreateModel(
            name='Pasos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(null=True, upload_to='pasos/')),
                ('completado', models.BooleanField(default=False)),
                ('tarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gca.informacion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='imagenes/avatar2.png', upload_to='avatar/', verbose_name='imagen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
